/**
 * analytics.types.ts
 *
 * Single source of truth for all Analytics page data contracts.
 * Mirrors analytics_data_contract.md exactly — no deviations.
 *
 * Canonical path: components/analytics/types/analytics.types.ts
 *
 * Architecture rules enforced here:
 * - Backend is authoritative for all scores, HP, XP, level, and shield.
 * - Frontend only formats and renders values received from the API.
 * - No derived financial calculations live on the frontend.
 */

// ─── Time Range ────────────────────────────────────────────────────────────────

export type TimeRange = '1W' | '1M' | '1Y' | 'All'

export const TIME_RANGE_OPTIONS: TimeRange[] = ['1W', '1M', '1Y', 'All']

// ─── Unlock Status ─────────────────────────────────────────────────────────────

export interface UnlockStatus {
  unlocked: boolean
  current_level: number
  /** Typed as literal 3 for contract clarity. Never read for logic. */
  required_level: 3
  xp_remaining: number
}

// ─── Shared: Health Status ────────────────────────────────────────────────────

/**
 * Three-tier health classification used across Debt and Loan Simulation.
 * Color semantics per DESIGN.md:
 *   good    → Muted Emerald (#0d9488)
 *   warning → Dawn Gold    (#f59e0b)
 *   bad     → Terracotta   (#e11d48)
 */
export type HealthStatus = 'good' | 'warning' | 'bad'

// ─── Financial Stability ───────────────────────────────────────────────────────

export interface FinancialStability {
  /**
   * Composite 0–100 score.
   * Backend-calculated exclusively.
   * Frontend MUST NOT derive or interpolate this value.
   */
  score: number
  /**
   * Signed delta vs the previous period.
   * Positive = improving. Negative = declining.
   */
  score_trend: number
  /** Human-readable explanation generated by the backend. */
  explanation: string
}

// ─── Advisory ─────────────────────────────────────────────────────────────────

/**
 * Priority order enforced by the backend (and documented in analytics_state_flow.md):
 *  1. debt_risk       — critical debt threshold breached
 *  2. payment_risk    — upcoming loan payment at risk
 *  3. overspending    — category limit exceeded
 *  4. savings_failure — savings target off track
 *  5. optimization    — general improvement suggestions
 *
 * Only one advisory may be active at a time.
 */
export type AdvisoryPriority =
  | 'debt_risk'
  | 'payment_risk'
  | 'overspending'
  | 'savings_failure'
  | 'optimization'

export interface ReductionTarget {
  category_name: string
  /** Amount in the user's local currency (integer, minor units per backend convention) */
  amount: number
}

export interface Advisory {
  priority: AdvisoryPriority
  headline: string
  recommendation: string
  /** 1–3 specific reduction targets that would resolve the advisory */
  reduction_targets: ReductionTarget[]
}

// ─── Cashflow ─────────────────────────────────────────────────────────────────

export interface CashflowDataPoint {
  /** ISO 8601 date string */
  date: string
  income: number
  expense: number
}

export interface Cashflow {
  /** Signed percentage. Positive = net cashflow improved vs comparison period. */
  trend_percentage: number
  /** Human-readable label, e.g. "vs last month" */
  comparison_period: string
  /**
   * Income = income transactions only.
   * Expense = expense transactions only.
   * Transfers are strictly excluded from both lines.
   */
  series: CashflowDataPoint[]
}

// ─── Income Allocation ────────────────────────────────────────────────────────

export interface IncomeAllocation {
  total_income: number
  /**
   * Sourced from the user's Baseline page settings.
   * Never derived from transaction history.
   */
  baseline_costs: number
  variable_spending: number
  /** Negative value indicates a deficit for the period */
  remaining_amount: number
}

// ─── Category Breakdown ───────────────────────────────────────────────────────

export interface CategoryBreakdown {
  category_id: string
  category_name: string
  amount: number
  /** 0–100, represents share of total spending */
  percentage: number
  /** True when amount > category_limit. Backend-evaluated. */
  overspending: boolean
}

// ─── Top Transactions ─────────────────────────────────────────────────────────

export interface TopTransaction {
  id: string
  /** Absolute expense amount (positive integer) */
  amount: number
  category_name: string
  wallet_name: string
  /** ISO 8601 date string */
  transaction_date: string
}

// ─── Debt Health ──────────────────────────────────────────────────────────────

export interface DebtHealth {
  /**
   * Debt-to-Income ratio: (Monthly Debt Payments / Monthly Income) * 100
   * Thresholds per PRD: good < 20, warning 21–35, bad > 35
   */
  dti_percentage: number
  status: HealthStatus
  active_loans: number
  /**
   * ISO 8601 date string.
   * Null when payment history is insufficient to estimate.
   * Display: "Unable to estimate" — never fabricate a date.
   */
  debt_free_date: string | null
  /** Backend-calculated maximum safe monthly debt capacity */
  safe_loan_limit: number
}

// ─── Asset Health ─────────────────────────────────────────────────────────────

export interface AssetHealth {
  /** Sum of bank and cash wallet balances */
  liquid_cash: number
  /**
   * Sum of investment account balances.
   * 0 when no investment assets are recorded — never null.
   */
  invested_assets: number
  /**
   * Liquid Cash / Average Monthly Expenses
   * Backend-calculated.
   */
  survival_runway_months: number
  /** 0–100 percentage toward the active savings target */
  savings_target_progress: number
}

// ─── Savings Target ───────────────────────────────────────────────────────────

/** One active savings target is supported in the current scope. */
export interface SavingsTarget {
  name: string
  amount: number
  /** ISO 8601 date string */
  deadline: string
}

// ─── Loan Simulation ──────────────────────────────────────────────────────────

export interface LoanSimulationRequest {
  monthly_installment: number
}

export interface LoanSimulationResult {
  projected_dti: number
  projected_status: HealthStatus
}

// ─── Rebalance Budget ─────────────────────────────────────────────────────────

export type RebalanceStrategy = 'reduce_others' | 'increase_overspent'

export interface RebalanceAdjustment {
  category_id: string
  category_name: string
  current_limit: number
  new_limit: number
}

export interface RebalanceBudgetPayload {
  strategy: RebalanceStrategy
  /**
   * Zero-sum invariant: sum of all limit reductions must equal overspent amount.
   * Backend validates before applying.
   */
  adjustments: RebalanceAdjustment[]
}

// ─── Analytics Bootstrap ──────────────────────────────────────────────────────

/**
 * Full response from GET /api/v1/analytics/bootstrap
 *
 * All sections are returned in one call to minimize waterfall fetches
 * on initial page load. Selective refresh endpoints handle mutations.
 */
export interface AnalyticsBootstrap {
  unlock_status: UnlockStatus
  /** Null when no active advisory exists (e.g., healthy finances) */
  advisory: Advisory | null
  financial_stability: FinancialStability
  cashflow: Cashflow
  income_allocation: IncomeAllocation
  category_breakdown: CategoryBreakdown[]
  debt_health: DebtHealth
  asset_health: AssetHealth
  /** Top 5 highest-expense transactions in the selected timeframe */
  top_transactions: TopTransaction[]
}

// ─── Section Keys ─────────────────────────────────────────────────────────────

/**
 * Identifies which analytics sections require selective refresh after a mutation.
 *
 * Mutation → Section refresh map (per analytics_state_flow.md):
 *   Transaction added   → cashflow, income_allocation, advisory
 *   Transaction edited  → affected sections only
 *   Transaction deleted → affected sections only
 *   Budget rebalanced   → advisory, income_allocation, category_breakdown
 */
export type AnalyticsSectionKey =
  | 'advisory'
  | 'cashflow'
  | 'income_allocation'
  | 'category_breakdown'
  | 'debt_health'
  | 'asset_health'
  | 'top_transactions'
